source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'acts-as-taggable-on'
gem 'authlogic'
gem 'bootsnap',     '>= 1.4.4', :require => false
gem 'coffee-rails'
gem 'jquery-rails'
gem 'pg',           '~> 1.1'
gem 'puma',         '~> 5.5'
gem 'rails',        '~> 7.0.0'
gem 'scrypt',       '~> 3.0'
gem 'sass-rails',   '>= 6'
gem 'mini_racer',   '~> 0.4.0'
gem 'turbolinks',   '~> 5'
gem 'uglifier'
gem 'will_paginate'

group :development do
  gem 'annotate'
  gem 'byebug'
  gem 'capistrano-rails',   :require => false
  gem 'highline'
  gem 'listen',             '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'stackprof'
  gem 'web-console',        '>= 4.1.0'

  # VSCode-related gems
  gem 'solargraph',       :require => false
  gem 'solargraph-rails', :require => false
end

group :test do
  gem 'docile',     '< 1.3.5' # Version 1.3.5 causes simplecov to barf
  gem 'mocha',      :require => false
  gem 'simplecov',  :require => false
end
