source 'https://rubygems.org'

gem 'acts_as_taggable'
gem 'authlogic'
gem 'mysql'
gem 'rails',            '2.3.18'
gem 'rake'
gem 'will_paginate',    '2.3.16'

group :test do
  gem 'mocha'
  gem 'simplecov'
  gem 'se_gem',         :git => 'git@github.com:ss/se_gem.git'
  gem 'turn'
end
