source 'https://rubygems.org'

gem 'acts_as_taggable', '2.0.2'
gem 'authlogic',        '2.1.1'
gem 'mysql',            '2.8.1'
gem 'rails',            '2.3.18'
gem 'rake',             '0.9.2.2'
gem 'will_paginate',    '2.3.11'

group :test do
  gem 'mocha',          '0.9.7'
  gem 'simplecov',      '0.7.1'
  gem 'se_gem',         :git => 'git@github.com:ss/se_gem.git'
  gem 'turn',           '0.9.6'
end
