# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 ts=2 et ai nowrap bg=dark :

Vagrant.configure('2') do |config|

  user = ENV['USER']
  raise "Unable to determine current user" unless user

  restart = false
  %w[
    vagrant-disksize
    vagrant-reload
  ].each do |plugin|
    unless Vagrant.has_plugin?(plugin)
      system "vagrant plugin install #{plugin}"
      restart = true
    end
  end

  if restart
    exec "vagrant " + ARGV.join(' ')
  end

  config.vm.box = 'ubuntu/focal64'
  config.disksize.size = '50GB'

  config.vm.provider "virtualbox" do |v|
    v.name = "Android Studio VM"
    v.gui = true
    v.cpus = 4
    v.memory = 2048

    v.customize ["modifyvm", :id, "--usb", "on"]
    # fix for slow network
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  [
    "sudo /vagrant/scripts/provision_vagrant.sh #{user}",
  ].each do |command|
    config.vm.provision :shell, :inline => command
  end

  # reboot the VM
  config.vm.provision :reload
end